/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/geocode-proxy/wrangler.toml --include-runtime=false workers/geocode-proxy/worker-configuration.d.ts` (hash: 64be9cb73f5ff2a2609dcae3325da7fc)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "https://fenlanddavid.github.io,http://localhost:5173,http://127.0.0.1:5173";
	GEOCODE_COORDINATOR: DurableObjectNamespace<import("./index").GeocodeCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GeocodeCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
