import React, { useEffect, useRef, useState } from "react";
import { Modal } from "./Modal";
import { db, Find, Media } from "../db";
import { generatePASDescription, calculateRecordingScore, getParishAndCounty } from "../services/pas";
import { getFLOForCounty } from "../services/flo";
import { getSetting } from "../services/data";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import {
  REPORT,
  ReportFooter,
  ReportHeader,
  ReportMetricGrid,
  ReportSectionHeading,
  ReportSummaryRows,
  formatReportDate,
  makeReportReference,
  applyReportPdfMetadata,
  reportBodyStyle,
  reportDocumentStyle,
} from "./ReportChrome";

interface PASReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  find: Find;
  photos: Media[];
}

const PASReportModal: React.FC<PASReportModalProps> = ({ isOpen, onClose, find, photos }) => {
  const [description, setDescription] = useState("");
  const [location, setLocation] = useState({ parish: "Loading...", county: "Loading..." });
  const [flo, setFlo] = useState<{ name: string; email: string } | null>(null);
  const [userName, setUserName] = useState("");
  const [userInitials, setUserInitials] = useState("FS");
  const [dailyCount, setDailyCount] = useState(1);
  const [score, setScore] = useState({ score: 0, reasons: [] as string[] });
  const [generating, setGenerating] = useState(false);
  const generatedAtRef = useRef(new Date());

  // Convert blobs to base64 data URLs — html2canvas cannot render blob: URLs
  const [photoUrls, setPhotoUrls] = useState<string[]>([]);

  useEffect(() => {
    let cancelled = false;
    Promise.all(
      photos.map(p => new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(p.blob);
      }))
    ).then(urls => { if (!cancelled) setPhotoUrls(urls); });
    return () => { cancelled = true; setPhotoUrls([]); };
  }, [photos]);

  useEffect(() => {
    if (isOpen) {
      setDescription(generatePASDescription(find));
      setScore(calculateRecordingScore(find, photos.length));
      
      getSetting("detectorist", "").then(name => {
          setUserName(name);
          if (name) {
              const initials = name.split(" ").map((n: string) => n[0]).join("").toUpperCase();
              setUserInitials(initials);
          }
      });

      // Calculate how many finds were recorded on this day for the daily count
      const reportDate = new Date(find.createdAt).toISOString().split('T')[0];
      db.finds.where("createdAt").startsWith(reportDate).count().then(count => {
          setDailyCount(count || 1);
      });

      if (find.lat != null && find.lon != null) {
        getParishAndCounty(find.lat, find.lon).then(loc => {
            setLocation(loc);
            const matchedFlo = getFLOForCounty(loc.county);
            setFlo(matchedFlo);
        });
      }
    }
  }, [isOpen, find, photos]);

  const getPDFBlob = async (): Promise<Blob | null> => {
    const element = document.getElementById("pas-report-preview");
    if (!element) return null;
    
    // Scale 3 for high-resolution photo rendering in the PDF
    const canvas = await html2canvas(element, { 
        scale: 3,
        useCORS: true,
        logging: false,
        backgroundColor: "#ffffff"
    });
    
    const imgData = canvas.toDataURL("image/jpeg", 0.95);
    const pdf = new jsPDF("p", "mm", "a4");
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    pdf.addImage(imgData, "JPEG", 0, 0, pdfWidth, pdfHeight);
    const generatedAt = generatedAtRef.current;
    const reference = makeReportReference("PAS", find.id || find.findCode || "LOCAL", generatedAt);
    applyReportPdfMetadata(pdf, {
      title: `PAS Draft Report - ${find.findCode || find.objectType || "Find"}`,
      subject: `${reference} generated by FindSpot for PAS recording support.`,
      reference,
      generatedAt,
    });
    return pdf.output("blob");
  };

  const generatePDF = async () => {
    setGenerating(true);
    try {
      const blob = await getPDFBlob();
      if (blob) {
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `PAS-Report-${find.findCode}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        setTimeout(() => URL.revokeObjectURL(url), 1000);
      }
    } catch (e) {
      console.error("PDF generation failed", e);
    }
    setGenerating(false);
  };

  const sendEmail = async () => {
    setGenerating(true);
    const recipient = flo ? flo.email : "";
    const subject = `PAS Submission: ${find.objectType} - ${find.findCode}`;
    const body = `
Hi,

I would like to record the following find:

Object: ${find.objectType}
Period: ${find.period}
Material: ${find.material}
Weight: ${find.weightG}g
NGR: ${find.osGridRef}
Parish: ${location.parish}
County: ${location.county}

Description:
${description}

Recorded via FindSpot
    `;

    try {
      const blob = await getPDFBlob();
      if (blob && navigator.canShare && navigator.canShare({ files: [new File([blob], "report.pdf", { type: "application/pdf" })] })) {
        const file = new File([blob], `PAS-Report-${find.findCode}.pdf`, { type: "application/pdf" });
        await navigator.share({
          title: subject,
          text: body,
          files: [file]
        });
      } else {
        window.location.href = `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
      }
    } catch (e) {
      console.error("Sharing failed", e);
    }
    setGenerating(false);
  };

  if (!isOpen) return null;

  const generatedAt = generatedAtRef.current;
  const reportReference = makeReportReference("PAS", find.id || find.findCode || "LOCAL", generatedAt);
  const recordId = `${userInitials}-${new Date(find.createdAt).toISOString().split("T")[0].replace(/-/g, "")}-${dailyCount}`;
  const hasGps = find.lat != null && find.lon != null;
  const hasDimensions = !!(find.widthMm || find.heightMm || find.depthMm);
  const targetFlo = flo ? `${flo.name} (${flo.email})` : "Not resolved";

  return (
    <Modal onClose={onClose} title="PAS Report Builder">
      <div className="flex flex-col gap-6">
        
        {/* Quality & Routing Header */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl p-4 flex items-center justify-between">
                <div>
                    <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Recording Quality</h3>
                    <p className="text-2xl font-black text-emerald-600 dark:text-emerald-400">{score.score}%</p>
                </div>
                <div className="flex flex-col gap-1 text-right">
                    {score.score >= 80 ? (
                        <span className="text-[8px] text-emerald-600 dark:text-emerald-400 font-bold uppercase">Professional</span>
                    ) : (
                        <span className="text-[8px] text-amber-600 dark:text-amber-400 font-bold uppercase">Missing data</span>
                    )}
                </div>
            </div>

            <div className={`border rounded-xl p-4 flex flex-col justify-center bg-white dark:bg-gray-900 ${flo ? 'border-emerald-200 dark:border-emerald-800' : 'border-gray-200 dark:border-gray-700 opacity-70'}`}>
                <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Target FLO</h3>
                <p className="text-sm font-black text-gray-800 dark:text-gray-100 truncate">{flo ? flo.name : "Detecting region..."}</p>
                <p className="text-[9px] text-gray-500 font-mono truncate">{flo ? flo.email : "Locating county..."}</p>
            </div>
        </div>

        {/* Data Quality Checklist */}
        <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl p-4">
            <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-3">Recording Checklist</h3>
            <div className="flex flex-col gap-2">
                <CheckItem label="GPS Coordinates" status={hasGps} />
                <CheckItem label="Object Weight" status={!!find.weightG} />
                <CheckItem label="Dimensions" status={hasDimensions} />
                <CheckItem label="Photos (Min 1)" status={photos.length >= 1} />
                <CheckItem label="Multi-Angle Photos (Min 3)" status={photos.length >= 3} />
            </div>
            {score.reasons.length > 0 && (
                <div className="mt-4 pt-3 border-t border-gray-100 dark:border-gray-800">
                    <p className="text-[10px] font-black text-amber-600 dark:text-amber-400 uppercase tracking-widest mb-1">To improve the record:</p>
                    <ul className="list-none p-0 m-0 flex flex-col gap-1">
                        {score.reasons.map((r, i) => (
                            <li key={i} className="text-[11px] text-gray-500 dark:text-gray-400 font-medium">{r}</li>
                        ))}
                    </ul>
                </div>
            )}
        </div>

        {/* Report Preview Card */}
        <div className="overflow-x-auto">
            <div id="pas-report-preview" style={{ ...reportDocumentStyle, minWidth: 680 }}>
                <ReportHeader
                  typeLabel="PAS Recording Report"
                  title={find.objectType || "Unidentified Find"}
                  subtitle={find.findCode}
                  reference={reportReference}
                  conductedBy={userName || "Detectorist"}
                  dateText={`Recorded ${formatReportDate(find.createdAt, "long") || "Unknown date"}`}
                  descriptor="Portable Antiquities Scheme recording pack prepared from local FindSpot data, including classification, location, photographs and draft object description."
                />

                <div style={reportBodyStyle}>
                  <ReportSummaryRows
                    title="PAS Record Details"
                    rows={[
                      { label: "Record ID", value: recordId },
                      { label: "Object", value: find.objectType || "Not recorded" },
                      { label: "Period", value: find.period || "Not recorded" },
                      { label: "Material", value: find.material || "Not recorded" },
                      { label: "Weight", value: find.weightG ? `${find.weightG}g` : "Not recorded" },
                      { label: "Grid reference", value: find.osGridRef || "Not recorded" },
                      { label: "Parish / county", value: `${location.parish || "Not resolved"} / ${location.county || "Not resolved"}` },
                      { label: "Target FLO", value: targetFlo },
                    ]}
                  />

                  <ReportMetricGrid
                    stats={[
                      { label: "Quality", value: `${score.score}%` },
                      { label: "Photos", value: String(photoUrls.length) },
                      { label: "GPS", value: hasGps ? "Yes" : "No" },
                    ]}
                  />

                  <div data-pdf-block>
                    <ReportSectionHeading caption="Photographic record for object identification and condition review.">
                      Photographic Evidence
                    </ReportSectionHeading>
                    <div style={{ display: "grid", gridTemplateColumns: photoUrls.length > 1 ? "repeat(2, 1fr)" : "1fr", gap: 10 }}>
                      {photoUrls.map((url, i) => (
                        <div key={i} style={{ background: REPORT.panel, border: `1px solid ${REPORT.line}`, borderRadius: 8, aspectRatio: "1 / 1", padding: 8, display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden" }}>
                          <img src={url} style={{ maxHeight: "100%", width: "100%", objectFit: "contain", display: "block" }} alt={`Plate ${i + 1}`} />
                        </div>
                      ))}
                      {photoUrls.length === 0 && (
                        <div style={{ background: REPORT.panelSoft, border: `1px solid ${REPORT.line}`, borderRadius: 8, minHeight: 180, display: "flex", alignItems: "center", justifyContent: "center", color: REPORT.muted, fontSize: 11, fontFamily: "sans-serif", fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase" }}>
                          No documentation images available
                        </div>
                      )}
                    </div>
                  </div>

                  <div data-pdf-block>
                    <ReportSectionHeading caption="Editable draft description generated from the find record. Review before submitting.">
                      Archaeological Description
                    </ReportSectionHeading>
                    <textarea
                      value={description}
                      onChange={(e) => setDescription(e.target.value)}
                      style={{
                        width: "100%",
                        minHeight: 150,
                        border: `1px solid ${REPORT.line}`,
                        borderRadius: 8,
                        background: REPORT.panel,
                        color: REPORT.ink,
                        padding: 12,
                        outline: "none",
                        resize: "none",
                        fontSize: 13,
                        lineHeight: 1.6,
                        fontFamily: "Georgia, serif",
                      }}
                    />
                  </div>

                  <ReportFooter
                    reference={reportReference}
                    generatedAt={generatedAt}
                    message="Prepared to support accurate archaeological recording."
                    note="Review this draft before submitting it to the Portable Antiquities Scheme or a Finds Liaison Officer. Treasure and other legally reportable finds must still be reported through the correct official process."
                  />
                </div>
            </div>
        </div>

        {/* Action Buttons */}
        <div className="grid grid-cols-2 gap-3 mt-2">
            <button 
                onClick={generatePDF}
                disabled={generating}
                className="bg-slate-800 hover:bg-slate-700 text-white font-black py-4 rounded-2xl flex items-center justify-center gap-2 uppercase tracking-widest text-[10px] border border-white/10 transition-all active:scale-95"
            >
                {generating ? "..." : (
                    <>
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                        Download PDF
                    </>
                )}
            </button>
            <button 
                onClick={sendEmail}
                className="bg-emerald-600 hover:bg-emerald-500 text-white font-black py-4 rounded-2xl flex items-center justify-center gap-2 uppercase tracking-widest text-[10px] shadow-lg shadow-emerald-900/20 transition-all active:scale-95"
            >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg>
                Send to FLO
            </button>
        </div>

      </div>
    </Modal>
  );
};

function CheckItem({ label, status }: { label: string; status: boolean }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-xs font-bold text-gray-700 dark:text-gray-300">{label}</span>
      {status ? (
        <span className="text-emerald-600 dark:text-emerald-400 font-black text-[10px] bg-emerald-500/10 px-2 py-1 rounded uppercase tracking-tighter">Verified</span>
      ) : (
        <span className="text-gray-500 dark:text-gray-400 font-black text-[10px] bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded uppercase tracking-tighter">Missing</span>
      )}
    </div>
  );
}

export default PASReportModal;
