export const FINDSPOT_COPYRIGHT_YEAR = "2026";

export const FINDSPOT_COPYRIGHT_NOTICE =
  "© 2026 FindSpot. All rights reserved.";

export const FINDSPOT_CORE_IP_NOTICE =
  "FindSpot, FieldGuide, FindShare, Club/Rally Reports, Landowner Reports and associated landscape analysis, reporting, agreement, event-sharing, club/rally administration and field-recording workflows are proprietary to FindSpot.";

export const FIELDGUIDE_PROPRIETARY_NOTICE =
  "FieldGuide is FindSpot's proprietary landscape intelligence engine. It combines terrain, LiDAR, satellite imagery, historic mapping, environmental, hydrology and archaeological context to help identify areas of likely past activity. FindSpot does not claim ownership of third-party source datasets, but the selection, combination, sequencing, transformation, weighting, scoring, classification and generated interpretation of those datasets within FieldGuide remain the intellectual property of FindSpot.";

export const FIELDGUIDE_SHORT_NOTICE =
  "FindSpot FieldGuide is proprietary landscape intelligence. Research aid only.";

export const FIELDGUIDE_USE_RESTRICTION =
  "FieldGuide analysis outputs are provided for field research support only and must not be copied, scraped, reverse engineered, commercially reused, or used to recreate competing systems without written permission.";

export const REPORT_PROTECTION_NOTICE =
  "Report design, template structure and generated interpretation are protected. User-submitted records remain owned by the user. Reuse or reproduction of this report format, workflow or generated analysis outside FindSpot requires permission.";

export const REPORT_FOOTER_NOTICE =
  `Generated by FindSpot · ${FINDSPOT_COPYRIGHT_NOTICE} · Report design and generated interpretation protected.`;

export const TERMS_OF_USE_VERSION = "2026-05-22";

export const TERMS_OF_USE_INTRO =
  "FindSpot is provided as a free fieldwork and recording tool for responsible metal detecting, permissions management, club/rally organisation and archaeological landscape research.";

export const TERMS_OF_USE_SECTIONS = [
  {
    title: "Free personal use",
    body: "FindSpot is currently provided for free personal use. There are no accounts or subscriptions built into this local-first app.",
  },
  {
    title: "User data stays local",
    body: "Users retain ownership of their own finds records, photographs, permission information, field boundaries and locally stored data. Saved data stays on the user's device unless the user chooses to export or share it.",
  },
  {
    title: "FindSpot ownership",
    body: "FindSpot retains ownership of the application, source code, interface design, branding, FieldGuide engine, FieldGuide outputs, report templates, agreement templates, share-card formats, Club/Rally Pack workflows, Club/Rally Reports, organiser merge flows, member export flows, classification language, interpretation structure, scoring systems and associated workflows.",
  },
  {
    title: "Permitted normal use",
    body: "Users may use FindSpot reports, agreements and exports for normal personal detecting, landowner communication, club/rally administration and responsible finds recording.",
  },
  {
    title: "No copying or commercial reuse",
    body: "Users may not copy, scrape, reverse engineer, decompile, reproduce, resell, redistribute, clone or commercially exploit FindSpot, FieldGuide, report templates, analysis outputs or generated interpretation systems without written permission.",
  },
  {
    title: "No competing-system training",
    body: "Users may not use FieldGuide outputs, scan results, classifications, scoring patterns or report structures to train, benchmark, develop or recreate a competing product or automated analysis system.",
  },
  {
    title: "Research aid only",
    body: "FieldGuide is intended as a landscape intelligence and research aid. It does not guarantee the presence of finds, archaeology, legal access, permission, safety or detecting suitability.",
  },
  {
    title: "User responsibility",
    body: "Use of FindSpot remains the responsibility of the user. Users must follow UK law, landowner agreements, detecting codes of practice, protected site restrictions and all relevant reporting requirements.",
  },
] as const;
