/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/findspot-static/wrangler.toml --include-runtime=false workers/findspot-static/worker-configuration.d.ts` (hash: 871aa875644dc373e92f370721c3a6f7)
interface __BaseEnv_Env {
	STATIC_BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
